/*
 * generated by Xtext 2.14.0
 */
package fr.tblf.energy.estimation.ui.tests;

import com.google.inject.Injector;
import fr.tblf.energy.estimation.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class EelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("fr.tblf.energy.estimation.Eel");
	}

}
