/*
 * generated by Xtext 2.14.0
 */
package fr.tblf.energy.estimation.eel.ui;

import com.google.inject.Injector;
import fr.tblf.energy.estimation.eel.ui.internal.EelActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(EelActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		EelActivator activator = EelActivator.getInstance();
		return activator != null ? activator.getInjector(EelActivator.FR_TBLF_ENERGY_ESTIMATION_EEL_EEL) : null;
	}

}
