/*
 * generated by Xtext 2.14.0
 */
package fr.tblf.energy.estimation.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEelScopeProvider extends DelegatingScopeProvider {
}
