/*
 * generated by Xtext 2.14.0
 */
package org.atlanmod.energy.estimation.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEelScopeProvider extends DelegatingScopeProvider {
}
