/**
 * generated by Xtext 2.14.0
 */
package fr.tblf.energy.estimation.eel;

import fr.tblf.energy.estimation.eel.AbstractEelRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EelRuntimeModule extends AbstractEelRuntimeModule {
}
