/**
 * generated by Xtext 2.14.0
 */
package fr.tblf.energy.estimation.eel;

import fr.tblf.energy.estimation.eel.EelStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EelStandaloneSetup extends EelStandaloneSetupGenerated {
  public static void doSetup() {
    new EelStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
