/*
 * generated by Xtext 2.14.0
 */
package org.atlanmod.energy.estimation.dsl.ui.tests;

import com.google.inject.Injector;
import org.atlanmod.energy.estimation.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class EelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("org.atlanmod.energy.estimation.dsl.Eel");
	}

}
