/**
 * generated by Xtext 2.14.0
 */
package fr.tblf.energy.estimation.eel.validation;

import fr.tblf.energy.estimation.eel.validation.AbstractEelValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EelValidator extends AbstractEelValidator {
}
