/**
 * generated by Xtext 2.14.0
 */
package fr.tblf.energy.estimation.eel.ui.contentassist;

import fr.tblf.energy.estimation.eel.ui.contentassist.AbstractEelProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EelProposalProvider extends AbstractEelProposalProvider {
}
