/*
 * generated by Xtext 2.14.0
 */
package fr.tblf.energy.estimation


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EelRuntimeModule extends AbstractEelRuntimeModule {
}
