/*
 * generated by Xtext 2.14.0
 */
package org.atlanmod.energy.estimation.dsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.atlanmod.energy.estimation.dsl.ide.contentassist.antlr.internal.InternalEelParser;
import org.atlanmod.energy.estimation.dsl.services.EelGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class EelParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(EelGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, EelGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getMeasureAccess().getAlternatives(), "rule__Measure__Alternatives");
			builder.put(grammarAccess.getCompositeMeasureAccess().getAlternatives(), "rule__CompositeMeasure__Alternatives");
			builder.put(grammarAccess.getMeasurementUncertaintyInformationAccess().getAlternatives(), "rule__MeasurementUncertaintyInformation__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getMeasureValue_ImplAccess().getAlternatives_5(), "rule__MeasureValue_Impl__Alternatives_5");
			builder.put(grammarAccess.getMeasureOCLAccess().getAlternatives_5(), "rule__MeasureOCL__Alternatives_5");
			builder.put(grammarAccess.getMeasureAttributeAccess().getAlternatives_5(), "rule__MeasureAttribute__Alternatives_5");
			builder.put(grammarAccess.getMeasureUnboundSumOperationAccess().getAlternatives_5(), "rule__MeasureUnboundSumOperation__Alternatives_5");
			builder.put(grammarAccess.getMeasureUnboundSubstractOperationAccess().getAlternatives_5(), "rule__MeasureUnboundSubstractOperation__Alternatives_5");
			builder.put(grammarAccess.getMeasureUnboundProductOperationAccess().getAlternatives_5(), "rule__MeasureUnboundProductOperation__Alternatives_5");
			builder.put(grammarAccess.getMeasureUnboundDivisionOperationAccess().getAlternatives_5(), "rule__MeasureUnboundDivisionOperation__Alternatives_5");
			builder.put(grammarAccess.getExponentialMeasureAccess().getAlternatives_5(), "rule__ExponentialMeasure__Alternatives_5");
			builder.put(grammarAccess.getLogisticMeasureAccess().getAlternatives_5(), "rule__LogisticMeasure__Alternatives_5");
			builder.put(grammarAccess.getIntegrationMeasureAccess().getAlternatives_5(), "rule__IntegrationMeasure__Alternatives_5");
			builder.put(grammarAccess.getEStructuralFeatureAccess().getAlternatives(), "rule__EStructuralFeature__Alternatives");
			builder.put(grammarAccess.getEClassifierAccess().getAlternatives(), "rule__EClassifier__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
			builder.put(grammarAccess.getVisibilityAccess().getAlternatives(), "rule__Visibility__Alternatives");
			builder.put(grammarAccess.getPlatformAccess().getGroup(), "rule__Platform__Group__0");
			builder.put(grammarAccess.getPlatformAccess().getGroup_4(), "rule__Platform__Group_4__0");
			builder.put(grammarAccess.getPlatformAccess().getGroup_4_3(), "rule__Platform__Group_4_3__0");
			builder.put(grammarAccess.getPlatformAccess().getGroup_5(), "rule__Platform__Group_5__0");
			builder.put(grammarAccess.getPlatformAccess().getGroup_5_3(), "rule__Platform__Group_5_3__0");
			builder.put(grammarAccess.getVariableAccess().getGroup(), "rule__Variable__Group__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_3(), "rule__Variable__Group_3__0");
			builder.put(grammarAccess.getEBigDecimalAccess().getGroup(), "rule__EBigDecimal__Group__0");
			builder.put(grammarAccess.getMeasureValue_ImplAccess().getGroup(), "rule__MeasureValue_Impl__Group__0");
			builder.put(grammarAccess.getMeasureValue_ImplAccess().getGroup_3(), "rule__MeasureValue_Impl__Group_3__0");
			builder.put(grammarAccess.getMeasureOCLAccess().getGroup(), "rule__MeasureOCL__Group__0");
			builder.put(grammarAccess.getMeasureOCLAccess().getGroup_3(), "rule__MeasureOCL__Group_3__0");
			builder.put(grammarAccess.getMeasureAttributeAccess().getGroup(), "rule__MeasureAttribute__Group__0");
			builder.put(grammarAccess.getMeasureAttributeAccess().getGroup_3(), "rule__MeasureAttribute__Group_3__0");
			builder.put(grammarAccess.getMeasureCastAccess().getGroup(), "rule__MeasureCast__Group__0");
			builder.put(grammarAccess.getMeasureCastAccess().getGroup_3(), "rule__MeasureCast__Group_3__0");
			builder.put(grammarAccess.getRealTimeDurationAccess().getGroup(), "rule__RealTimeDuration__Group__0");
			builder.put(grammarAccess.getRealTimeDurationAccess().getGroup_3(), "rule__RealTimeDuration__Group_3__0");
			builder.put(grammarAccess.getMeasureUnboundSumOperationAccess().getGroup(), "rule__MeasureUnboundSumOperation__Group__0");
			builder.put(grammarAccess.getMeasureUnboundSumOperationAccess().getGroup_3(), "rule__MeasureUnboundSumOperation__Group_3__0");
			builder.put(grammarAccess.getMeasureUnboundSumOperationAccess().getGroup_8(), "rule__MeasureUnboundSumOperation__Group_8__0");
			builder.put(grammarAccess.getMeasureUnboundSubstractOperationAccess().getGroup(), "rule__MeasureUnboundSubstractOperation__Group__0");
			builder.put(grammarAccess.getMeasureUnboundSubstractOperationAccess().getGroup_3(), "rule__MeasureUnboundSubstractOperation__Group_3__0");
			builder.put(grammarAccess.getMeasureUnboundSubstractOperationAccess().getGroup_8(), "rule__MeasureUnboundSubstractOperation__Group_8__0");
			builder.put(grammarAccess.getMeasureUnboundProductOperationAccess().getGroup(), "rule__MeasureUnboundProductOperation__Group__0");
			builder.put(grammarAccess.getMeasureUnboundProductOperationAccess().getGroup_3(), "rule__MeasureUnboundProductOperation__Group_3__0");
			builder.put(grammarAccess.getMeasureUnboundProductOperationAccess().getGroup_8(), "rule__MeasureUnboundProductOperation__Group_8__0");
			builder.put(grammarAccess.getMeasureUnboundDivisionOperationAccess().getGroup(), "rule__MeasureUnboundDivisionOperation__Group__0");
			builder.put(grammarAccess.getMeasureUnboundDivisionOperationAccess().getGroup_3(), "rule__MeasureUnboundDivisionOperation__Group_3__0");
			builder.put(grammarAccess.getMeasureUnboundDivisionOperationAccess().getGroup_8(), "rule__MeasureUnboundDivisionOperation__Group_8__0");
			builder.put(grammarAccess.getExponentialMeasureAccess().getGroup(), "rule__ExponentialMeasure__Group__0");
			builder.put(grammarAccess.getExponentialMeasureAccess().getGroup_3(), "rule__ExponentialMeasure__Group_3__0");
			builder.put(grammarAccess.getLogisticMeasureAccess().getGroup(), "rule__LogisticMeasure__Group__0");
			builder.put(grammarAccess.getLogisticMeasureAccess().getGroup_3(), "rule__LogisticMeasure__Group_3__0");
			builder.put(grammarAccess.getIntegrationMeasureAccess().getGroup(), "rule__IntegrationMeasure__Group__0");
			builder.put(grammarAccess.getIntegrationMeasureAccess().getGroup_3(), "rule__IntegrationMeasure__Group_3__0");
			builder.put(grammarAccess.getMeasurementUncertaintyAccess().getGroup(), "rule__MeasurementUncertainty__Group__0");
			builder.put(grammarAccess.getMeasurementUncertaintyAccess().getGroup_3(), "rule__MeasurementUncertainty__Group_3__0");
			builder.put(grammarAccess.getMeasurementUncertaintyAccess().getGroup_4(), "rule__MeasurementUncertainty__Group_4__0");
			builder.put(grammarAccess.getNormalDistributionAccess().getGroup(), "rule__NormalDistribution__Group__0");
			builder.put(grammarAccess.getIntervalAccess().getGroup(), "rule__Interval__Group__0");
			builder.put(grammarAccess.getSamplingAccess().getGroup(), "rule__Sampling__Group__0");
			builder.put(grammarAccess.getSamplingAccess().getGroup_3(), "rule__Sampling__Group_3__0");
			builder.put(grammarAccess.getSamplingAccess().getGroup_4(), "rule__Sampling__Group_4__0");
			builder.put(grammarAccess.getSamplingAccess().getGroup_4_3(), "rule__Sampling__Group_4_3__0");
			builder.put(grammarAccess.getIntegralAccess().getGroup(), "rule__Integral__Group__0");
			builder.put(grammarAccess.getIntegralAccess().getGroup_2(), "rule__Integral__Group_2__0");
			builder.put(grammarAccess.getSampleAccess().getGroup(), "rule__Sample__Group__0");
			builder.put(grammarAccess.getSampleAccess().getGroup_3(), "rule__Sample__Group_3__0");
			builder.put(grammarAccess.getSampleAccess().getGroup_3_3(), "rule__Sample__Group_3_3__0");
			builder.put(grammarAccess.getEClassAccess().getGroup(), "rule__EClass__Group__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_6(), "rule__EClass__Group_6__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_7(), "rule__EClass__Group_7__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_8(), "rule__EClass__Group_8__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_8_3(), "rule__EClass__Group_8_3__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_9(), "rule__EClass__Group_9__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_9_3(), "rule__EClass__Group_9_3__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_10(), "rule__EClass__Group_10__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_10_3(), "rule__EClass__Group_10_3__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_11(), "rule__EClass__Group_11__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_11_3(), "rule__EClass__Group_11_3__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_12(), "rule__EClass__Group_12__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_12_3(), "rule__EClass__Group_12_3__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_13(), "rule__EClass__Group_13__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_13_3(), "rule__EClass__Group_13_3__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup(), "rule__EOperation__Group__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_4(), "rule__EOperation__Group_4__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_5(), "rule__EOperation__Group_5__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_6(), "rule__EOperation__Group_6__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_7(), "rule__EOperation__Group_7__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_8(), "rule__EOperation__Group_8__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_9(), "rule__EOperation__Group_9__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_9_3(), "rule__EOperation__Group_9_3__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_10(), "rule__EOperation__Group_10__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_10_3(), "rule__EOperation__Group_10_3__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_11(), "rule__EOperation__Group_11__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_12(), "rule__EOperation__Group_12__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_12_3(), "rule__EOperation__Group_12_3__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_13(), "rule__EOperation__Group_13__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_13_3(), "rule__EOperation__Group_13_3__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_14(), "rule__EOperation__Group_14__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_14_3(), "rule__EOperation__Group_14_3__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup(), "rule__EAnnotation__Group__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_3(), "rule__EAnnotation__Group_3__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_4(), "rule__EAnnotation__Group_4__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_4_3(), "rule__EAnnotation__Group_4_3__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_5(), "rule__EAnnotation__Group_5__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_5_3(), "rule__EAnnotation__Group_5_3__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_6(), "rule__EAnnotation__Group_6__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_6_3(), "rule__EAnnotation__Group_6_3__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_7(), "rule__EAnnotation__Group_7__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_7_3(), "rule__EAnnotation__Group_7_3__0");
			builder.put(grammarAccess.getETypeParameterAccess().getGroup(), "rule__ETypeParameter__Group__0");
			builder.put(grammarAccess.getETypeParameterAccess().getGroup_4(), "rule__ETypeParameter__Group_4__0");
			builder.put(grammarAccess.getETypeParameterAccess().getGroup_4_3(), "rule__ETypeParameter__Group_4_3__0");
			builder.put(grammarAccess.getETypeParameterAccess().getGroup_5(), "rule__ETypeParameter__Group_5__0");
			builder.put(grammarAccess.getETypeParameterAccess().getGroup_5_3(), "rule__ETypeParameter__Group_5_3__0");
			builder.put(grammarAccess.getEGenericTypeAccess().getGroup(), "rule__EGenericType__Group__0");
			builder.put(grammarAccess.getEGenericTypeAccess().getGroup_3(), "rule__EGenericType__Group_3__0");
			builder.put(grammarAccess.getEGenericTypeAccess().getGroup_4(), "rule__EGenericType__Group_4__0");
			builder.put(grammarAccess.getEGenericTypeAccess().getGroup_5(), "rule__EGenericType__Group_5__0");
			builder.put(grammarAccess.getEGenericTypeAccess().getGroup_6(), "rule__EGenericType__Group_6__0");
			builder.put(grammarAccess.getEGenericTypeAccess().getGroup_6_3(), "rule__EGenericType__Group_6_3__0");
			builder.put(grammarAccess.getEGenericTypeAccess().getGroup_7(), "rule__EGenericType__Group_7__0");
			builder.put(grammarAccess.getEStringToStringMapEntryAccess().getGroup(), "rule__EStringToStringMapEntry__Group__0");
			builder.put(grammarAccess.getEStringToStringMapEntryAccess().getGroup_3(), "rule__EStringToStringMapEntry__Group_3__0");
			builder.put(grammarAccess.getEStringToStringMapEntryAccess().getGroup_4(), "rule__EStringToStringMapEntry__Group_4__0");
			builder.put(grammarAccess.getEObjectAccess().getGroup(), "rule__EObject__Group__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup(), "rule__EAttribute__Group__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_9(), "rule__EAttribute__Group_9__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_10(), "rule__EAttribute__Group_10__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_11(), "rule__EAttribute__Group_11__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_12(), "rule__EAttribute__Group_12__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_13(), "rule__EAttribute__Group_13__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_14(), "rule__EAttribute__Group_14__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_15(), "rule__EAttribute__Group_15__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_16(), "rule__EAttribute__Group_16__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_16_3(), "rule__EAttribute__Group_16_3__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_17(), "rule__EAttribute__Group_17__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup(), "rule__EReference__Group__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_9(), "rule__EReference__Group_9__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_10(), "rule__EReference__Group_10__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_11(), "rule__EReference__Group_11__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_12(), "rule__EReference__Group_12__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_13(), "rule__EReference__Group_13__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_14(), "rule__EReference__Group_14__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_15(), "rule__EReference__Group_15__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_16(), "rule__EReference__Group_16__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_17(), "rule__EReference__Group_17__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_18(), "rule__EReference__Group_18__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_18_3(), "rule__EReference__Group_18_3__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_19(), "rule__EReference__Group_19__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_19_3(), "rule__EReference__Group_19_3__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_20(), "rule__EReference__Group_20__0");
			builder.put(grammarAccess.getEDataType_ImplAccess().getGroup(), "rule__EDataType_Impl__Group__0");
			builder.put(grammarAccess.getEDataType_ImplAccess().getGroup_4(), "rule__EDataType_Impl__Group_4__0");
			builder.put(grammarAccess.getEDataType_ImplAccess().getGroup_5(), "rule__EDataType_Impl__Group_5__0");
			builder.put(grammarAccess.getEDataType_ImplAccess().getGroup_6(), "rule__EDataType_Impl__Group_6__0");
			builder.put(grammarAccess.getEDataType_ImplAccess().getGroup_7(), "rule__EDataType_Impl__Group_7__0");
			builder.put(grammarAccess.getEDataType_ImplAccess().getGroup_7_3(), "rule__EDataType_Impl__Group_7_3__0");
			builder.put(grammarAccess.getEDataType_ImplAccess().getGroup_8(), "rule__EDataType_Impl__Group_8__0");
			builder.put(grammarAccess.getEDataType_ImplAccess().getGroup_8_3(), "rule__EDataType_Impl__Group_8_3__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup(), "rule__EEnum__Group__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_4(), "rule__EEnum__Group_4__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_5(), "rule__EEnum__Group_5__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_6(), "rule__EEnum__Group_6__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_7(), "rule__EEnum__Group_7__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_7_3(), "rule__EEnum__Group_7_3__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_8(), "rule__EEnum__Group_8__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_8_3(), "rule__EEnum__Group_8_3__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_9(), "rule__EEnum__Group_9__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_9_3(), "rule__EEnum__Group_9_3__0");
			builder.put(grammarAccess.getEEnumLiteralAccess().getGroup(), "rule__EEnumLiteral__Group__0");
			builder.put(grammarAccess.getEEnumLiteralAccess().getGroup_4(), "rule__EEnumLiteral__Group_4__0");
			builder.put(grammarAccess.getEEnumLiteralAccess().getGroup_5(), "rule__EEnumLiteral__Group_5__0");
			builder.put(grammarAccess.getEEnumLiteralAccess().getGroup_6(), "rule__EEnumLiteral__Group_6__0");
			builder.put(grammarAccess.getEEnumLiteralAccess().getGroup_6_3(), "rule__EEnumLiteral__Group_6_3__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup(), "rule__EParameter__Group__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_4(), "rule__EParameter__Group_4__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_5(), "rule__EParameter__Group_5__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_6(), "rule__EParameter__Group_6__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_7(), "rule__EParameter__Group_7__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_8(), "rule__EParameter__Group_8__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_9(), "rule__EParameter__Group_9__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_9_3(), "rule__EParameter__Group_9_3__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_10(), "rule__EParameter__Group_10__0");
			builder.put(grammarAccess.getPlatformAccess().getNameAssignment_2(), "rule__Platform__NameAssignment_2");
			builder.put(grammarAccess.getPlatformAccess().getVariablesAssignment_4_2(), "rule__Platform__VariablesAssignment_4_2");
			builder.put(grammarAccess.getPlatformAccess().getVariablesAssignment_4_3_1(), "rule__Platform__VariablesAssignment_4_3_1");
			builder.put(grammarAccess.getPlatformAccess().getMeasuresAssignment_5_2(), "rule__Platform__MeasuresAssignment_5_2");
			builder.put(grammarAccess.getPlatformAccess().getMeasuresAssignment_5_3_1(), "rule__Platform__MeasuresAssignment_5_3_1");
			builder.put(grammarAccess.getVariableAccess().getNameAssignment_1(), "rule__Variable__NameAssignment_1");
			builder.put(grammarAccess.getVariableAccess().getValueAssignment_3_1(), "rule__Variable__ValueAssignment_3_1");
			builder.put(grammarAccess.getVariableAccess().getVibilityAssignment_5(), "rule__Variable__VibilityAssignment_5");
			builder.put(grammarAccess.getMeasureValue_ImplAccess().getPostAssignment_1(), "rule__MeasureValue_Impl__PostAssignment_1");
			builder.put(grammarAccess.getMeasureValue_ImplAccess().getTargetClassAssignment_2(), "rule__MeasureValue_Impl__TargetClassAssignment_2");
			builder.put(grammarAccess.getMeasureValue_ImplAccess().getTargetOperationAssignment_3_1(), "rule__MeasureValue_Impl__TargetOperationAssignment_3_1");
			builder.put(grammarAccess.getMeasureValue_ImplAccess().getTypeAssignment_5_0(), "rule__MeasureValue_Impl__TypeAssignment_5_0");
			builder.put(grammarAccess.getMeasureValue_ImplAccess().getSubnameAssignment_5_1(), "rule__MeasureValue_Impl__SubnameAssignment_5_1");
			builder.put(grammarAccess.getMeasureValue_ImplAccess().getValueAssignment_7(), "rule__MeasureValue_Impl__ValueAssignment_7");
			builder.put(grammarAccess.getMeasureOCLAccess().getPostAssignment_1(), "rule__MeasureOCL__PostAssignment_1");
			builder.put(grammarAccess.getMeasureOCLAccess().getTargetClassAssignment_2(), "rule__MeasureOCL__TargetClassAssignment_2");
			builder.put(grammarAccess.getMeasureOCLAccess().getTargetOperationAssignment_3_1(), "rule__MeasureOCL__TargetOperationAssignment_3_1");
			builder.put(grammarAccess.getMeasureOCLAccess().getTypeAssignment_5_0(), "rule__MeasureOCL__TypeAssignment_5_0");
			builder.put(grammarAccess.getMeasureOCLAccess().getSubnameAssignment_5_1(), "rule__MeasureOCL__SubnameAssignment_5_1");
			builder.put(grammarAccess.getMeasureOCLAccess().getOclQueryAssignment_8(), "rule__MeasureOCL__OclQueryAssignment_8");
			builder.put(grammarAccess.getMeasureAttributeAccess().getPostAssignment_1(), "rule__MeasureAttribute__PostAssignment_1");
			builder.put(grammarAccess.getMeasureAttributeAccess().getTargetClassAssignment_2(), "rule__MeasureAttribute__TargetClassAssignment_2");
			builder.put(grammarAccess.getMeasureAttributeAccess().getTargetOperationAssignment_3_1(), "rule__MeasureAttribute__TargetOperationAssignment_3_1");
			builder.put(grammarAccess.getMeasureAttributeAccess().getTypeAssignment_5_0(), "rule__MeasureAttribute__TypeAssignment_5_0");
			builder.put(grammarAccess.getMeasureAttributeAccess().getSubnameAssignment_5_1(), "rule__MeasureAttribute__SubnameAssignment_5_1");
			builder.put(grammarAccess.getMeasureAttributeAccess().getAttAssignment_8(), "rule__MeasureAttribute__AttAssignment_8");
			builder.put(grammarAccess.getMeasureCastAccess().getPostAssignment_1(), "rule__MeasureCast__PostAssignment_1");
			builder.put(grammarAccess.getMeasureCastAccess().getTargetClassAssignment_2(), "rule__MeasureCast__TargetClassAssignment_2");
			builder.put(grammarAccess.getMeasureCastAccess().getTargetOperationAssignment_3_1(), "rule__MeasureCast__TargetOperationAssignment_3_1");
			builder.put(grammarAccess.getMeasureCastAccess().getSubnameAssignment_5(), "rule__MeasureCast__SubnameAssignment_5");
			builder.put(grammarAccess.getMeasureCastAccess().getMeasureAssignment_7(), "rule__MeasureCast__MeasureAssignment_7");
			builder.put(grammarAccess.getMeasureCastAccess().getTypeAssignment_9(), "rule__MeasureCast__TypeAssignment_9");
			builder.put(grammarAccess.getRealTimeDurationAccess().getPostAssignment_1(), "rule__RealTimeDuration__PostAssignment_1");
			builder.put(grammarAccess.getRealTimeDurationAccess().getTargetClassAssignment_2(), "rule__RealTimeDuration__TargetClassAssignment_2");
			builder.put(grammarAccess.getRealTimeDurationAccess().getTargetOperationAssignment_3_1(), "rule__RealTimeDuration__TargetOperationAssignment_3_1");
			builder.put(grammarAccess.getMeasureUnboundSumOperationAccess().getPostAssignment_1(), "rule__MeasureUnboundSumOperation__PostAssignment_1");
			builder.put(grammarAccess.getMeasureUnboundSumOperationAccess().getTargetClassAssignment_2(), "rule__MeasureUnboundSumOperation__TargetClassAssignment_2");
			builder.put(grammarAccess.getMeasureUnboundSumOperationAccess().getTargetOperationAssignment_3_1(), "rule__MeasureUnboundSumOperation__TargetOperationAssignment_3_1");
			builder.put(grammarAccess.getMeasureUnboundSumOperationAccess().getTypeAssignment_5_0(), "rule__MeasureUnboundSumOperation__TypeAssignment_5_0");
			builder.put(grammarAccess.getMeasureUnboundSumOperationAccess().getSubnameAssignment_5_1(), "rule__MeasureUnboundSumOperation__SubnameAssignment_5_1");
			builder.put(grammarAccess.getMeasureUnboundSumOperationAccess().getMeasuresAssignment_7(), "rule__MeasureUnboundSumOperation__MeasuresAssignment_7");
			builder.put(grammarAccess.getMeasureUnboundSumOperationAccess().getMeasuresAssignment_8_1(), "rule__MeasureUnboundSumOperation__MeasuresAssignment_8_1");
			builder.put(grammarAccess.getMeasureUnboundSubstractOperationAccess().getPostAssignment_1(), "rule__MeasureUnboundSubstractOperation__PostAssignment_1");
			builder.put(grammarAccess.getMeasureUnboundSubstractOperationAccess().getTargetClassAssignment_2(), "rule__MeasureUnboundSubstractOperation__TargetClassAssignment_2");
			builder.put(grammarAccess.getMeasureUnboundSubstractOperationAccess().getTargetOperationAssignment_3_1(), "rule__MeasureUnboundSubstractOperation__TargetOperationAssignment_3_1");
			builder.put(grammarAccess.getMeasureUnboundSubstractOperationAccess().getTypeAssignment_5_0(), "rule__MeasureUnboundSubstractOperation__TypeAssignment_5_0");
			builder.put(grammarAccess.getMeasureUnboundSubstractOperationAccess().getSubnameAssignment_5_1(), "rule__MeasureUnboundSubstractOperation__SubnameAssignment_5_1");
			builder.put(grammarAccess.getMeasureUnboundSubstractOperationAccess().getMeasuresAssignment_7(), "rule__MeasureUnboundSubstractOperation__MeasuresAssignment_7");
			builder.put(grammarAccess.getMeasureUnboundSubstractOperationAccess().getMeasuresAssignment_8_1(), "rule__MeasureUnboundSubstractOperation__MeasuresAssignment_8_1");
			builder.put(grammarAccess.getMeasureUnboundProductOperationAccess().getPostAssignment_1(), "rule__MeasureUnboundProductOperation__PostAssignment_1");
			builder.put(grammarAccess.getMeasureUnboundProductOperationAccess().getTargetClassAssignment_2(), "rule__MeasureUnboundProductOperation__TargetClassAssignment_2");
			builder.put(grammarAccess.getMeasureUnboundProductOperationAccess().getTargetOperationAssignment_3_1(), "rule__MeasureUnboundProductOperation__TargetOperationAssignment_3_1");
			builder.put(grammarAccess.getMeasureUnboundProductOperationAccess().getTypeAssignment_5_0(), "rule__MeasureUnboundProductOperation__TypeAssignment_5_0");
			builder.put(grammarAccess.getMeasureUnboundProductOperationAccess().getSubnameAssignment_5_1(), "rule__MeasureUnboundProductOperation__SubnameAssignment_5_1");
			builder.put(grammarAccess.getMeasureUnboundProductOperationAccess().getMeasuresAssignment_7(), "rule__MeasureUnboundProductOperation__MeasuresAssignment_7");
			builder.put(grammarAccess.getMeasureUnboundProductOperationAccess().getMeasuresAssignment_8_1(), "rule__MeasureUnboundProductOperation__MeasuresAssignment_8_1");
			builder.put(grammarAccess.getMeasureUnboundDivisionOperationAccess().getPostAssignment_1(), "rule__MeasureUnboundDivisionOperation__PostAssignment_1");
			builder.put(grammarAccess.getMeasureUnboundDivisionOperationAccess().getTargetClassAssignment_2(), "rule__MeasureUnboundDivisionOperation__TargetClassAssignment_2");
			builder.put(grammarAccess.getMeasureUnboundDivisionOperationAccess().getTargetOperationAssignment_3_1(), "rule__MeasureUnboundDivisionOperation__TargetOperationAssignment_3_1");
			builder.put(grammarAccess.getMeasureUnboundDivisionOperationAccess().getTypeAssignment_5_0(), "rule__MeasureUnboundDivisionOperation__TypeAssignment_5_0");
			builder.put(grammarAccess.getMeasureUnboundDivisionOperationAccess().getSubnameAssignment_5_1(), "rule__MeasureUnboundDivisionOperation__SubnameAssignment_5_1");
			builder.put(grammarAccess.getMeasureUnboundDivisionOperationAccess().getMeasuresAssignment_7(), "rule__MeasureUnboundDivisionOperation__MeasuresAssignment_7");
			builder.put(grammarAccess.getMeasureUnboundDivisionOperationAccess().getMeasuresAssignment_8_1(), "rule__MeasureUnboundDivisionOperation__MeasuresAssignment_8_1");
			builder.put(grammarAccess.getExponentialMeasureAccess().getPostAssignment_1(), "rule__ExponentialMeasure__PostAssignment_1");
			builder.put(grammarAccess.getExponentialMeasureAccess().getTargetClassAssignment_2(), "rule__ExponentialMeasure__TargetClassAssignment_2");
			builder.put(grammarAccess.getExponentialMeasureAccess().getTargetOperationAssignment_3_1(), "rule__ExponentialMeasure__TargetOperationAssignment_3_1");
			builder.put(grammarAccess.getExponentialMeasureAccess().getTypeAssignment_5_0(), "rule__ExponentialMeasure__TypeAssignment_5_0");
			builder.put(grammarAccess.getExponentialMeasureAccess().getSubnameAssignment_5_1(), "rule__ExponentialMeasure__SubnameAssignment_5_1");
			builder.put(grammarAccess.getExponentialMeasureAccess().getXAssignment_8(), "rule__ExponentialMeasure__XAssignment_8");
			builder.put(grammarAccess.getLogisticMeasureAccess().getPostAssignment_1(), "rule__LogisticMeasure__PostAssignment_1");
			builder.put(grammarAccess.getLogisticMeasureAccess().getTargetClassAssignment_2(), "rule__LogisticMeasure__TargetClassAssignment_2");
			builder.put(grammarAccess.getLogisticMeasureAccess().getTargetOperationAssignment_3_1(), "rule__LogisticMeasure__TargetOperationAssignment_3_1");
			builder.put(grammarAccess.getLogisticMeasureAccess().getTypeAssignment_5_0(), "rule__LogisticMeasure__TypeAssignment_5_0");
			builder.put(grammarAccess.getLogisticMeasureAccess().getSubnameAssignment_5_1(), "rule__LogisticMeasure__SubnameAssignment_5_1");
			builder.put(grammarAccess.getLogisticMeasureAccess().getLAssignment_8(), "rule__LogisticMeasure__LAssignment_8");
			builder.put(grammarAccess.getLogisticMeasureAccess().getKAssignment_9(), "rule__LogisticMeasure__KAssignment_9");
			builder.put(grammarAccess.getLogisticMeasureAccess().getX0Assignment_10(), "rule__LogisticMeasure__X0Assignment_10");
			builder.put(grammarAccess.getLogisticMeasureAccess().getXAssignment_11(), "rule__LogisticMeasure__XAssignment_11");
			builder.put(grammarAccess.getIntegrationMeasureAccess().getPostAssignment_1(), "rule__IntegrationMeasure__PostAssignment_1");
			builder.put(grammarAccess.getIntegrationMeasureAccess().getTargetClassAssignment_2(), "rule__IntegrationMeasure__TargetClassAssignment_2");
			builder.put(grammarAccess.getIntegrationMeasureAccess().getTargetOperationAssignment_3_1(), "rule__IntegrationMeasure__TargetOperationAssignment_3_1");
			builder.put(grammarAccess.getIntegrationMeasureAccess().getTypeAssignment_5_0(), "rule__IntegrationMeasure__TypeAssignment_5_0");
			builder.put(grammarAccess.getIntegrationMeasureAccess().getSubnameAssignment_5_1(), "rule__IntegrationMeasure__SubnameAssignment_5_1");
			builder.put(grammarAccess.getIntegrationMeasureAccess().getFunctionAssignment_8(), "rule__IntegrationMeasure__FunctionAssignment_8");
			builder.put(grammarAccess.getIntegrationMeasureAccess().getLeftBoundAssignment_10(), "rule__IntegrationMeasure__LeftBoundAssignment_10");
			builder.put(grammarAccess.getIntegrationMeasureAccess().getRightBoundAssignment_12(), "rule__IntegrationMeasure__RightBoundAssignment_12");
			builder.put(grammarAccess.getMeasurementUncertaintyAccess().getStandardUncertaintyAssignment_3_1(), "rule__MeasurementUncertainty__StandardUncertaintyAssignment_3_1");
			builder.put(grammarAccess.getMeasurementUncertaintyAccess().getInformationAssignment_4_1(), "rule__MeasurementUncertainty__InformationAssignment_4_1");
			builder.put(grammarAccess.getIntervalAccess().getLowerEndpointAssignment_3(), "rule__Interval__LowerEndpointAssignment_3");
			builder.put(grammarAccess.getIntervalAccess().getUpperEndpointAssignment_5(), "rule__Interval__UpperEndpointAssignment_5");
			builder.put(grammarAccess.getSamplingAccess().getMeasurementProcedureAssignment_3_1(), "rule__Sampling__MeasurementProcedureAssignment_3_1");
			builder.put(grammarAccess.getSamplingAccess().getSamplesAssignment_4_2(), "rule__Sampling__SamplesAssignment_4_2");
			builder.put(grammarAccess.getSamplingAccess().getSamplesAssignment_4_3_1(), "rule__Sampling__SamplesAssignment_4_3_1");
			builder.put(grammarAccess.getIntegralAccess().getFunctionAssignment_2_1(), "rule__Integral__FunctionAssignment_2_1");
			builder.put(grammarAccess.getIntegralAccess().getIntervalAssignment_4(), "rule__Integral__IntervalAssignment_4");
			builder.put(grammarAccess.getSampleAccess().getQuantityAssignment_3_2(), "rule__Sample__QuantityAssignment_3_2");
			builder.put(grammarAccess.getSampleAccess().getQuantityAssignment_3_3_1(), "rule__Sample__QuantityAssignment_3_3_1");
			builder.put(grammarAccess.getEClassAccess().getAbstractAssignment_1(), "rule__EClass__AbstractAssignment_1");
			builder.put(grammarAccess.getEClassAccess().getInterfaceAssignment_2(), "rule__EClass__InterfaceAssignment_2");
			builder.put(grammarAccess.getEClassAccess().getNameAssignment_4(), "rule__EClass__NameAssignment_4");
			builder.put(grammarAccess.getEClassAccess().getInstanceClassNameAssignment_6_1(), "rule__EClass__InstanceClassNameAssignment_6_1");
			builder.put(grammarAccess.getEClassAccess().getInstanceTypeNameAssignment_7_1(), "rule__EClass__InstanceTypeNameAssignment_7_1");
			builder.put(grammarAccess.getEClassAccess().getESuperTypesAssignment_8_2(), "rule__EClass__ESuperTypesAssignment_8_2");
			builder.put(grammarAccess.getEClassAccess().getESuperTypesAssignment_8_3_1(), "rule__EClass__ESuperTypesAssignment_8_3_1");
			builder.put(grammarAccess.getEClassAccess().getEAnnotationsAssignment_9_2(), "rule__EClass__EAnnotationsAssignment_9_2");
			builder.put(grammarAccess.getEClassAccess().getEAnnotationsAssignment_9_3_1(), "rule__EClass__EAnnotationsAssignment_9_3_1");
			builder.put(grammarAccess.getEClassAccess().getETypeParametersAssignment_10_2(), "rule__EClass__ETypeParametersAssignment_10_2");
			builder.put(grammarAccess.getEClassAccess().getETypeParametersAssignment_10_3_1(), "rule__EClass__ETypeParametersAssignment_10_3_1");
			builder.put(grammarAccess.getEClassAccess().getEOperationsAssignment_11_2(), "rule__EClass__EOperationsAssignment_11_2");
			builder.put(grammarAccess.getEClassAccess().getEOperationsAssignment_11_3_1(), "rule__EClass__EOperationsAssignment_11_3_1");
			builder.put(grammarAccess.getEClassAccess().getEStructuralFeaturesAssignment_12_2(), "rule__EClass__EStructuralFeaturesAssignment_12_2");
			builder.put(grammarAccess.getEClassAccess().getEStructuralFeaturesAssignment_12_3_1(), "rule__EClass__EStructuralFeaturesAssignment_12_3_1");
			builder.put(grammarAccess.getEClassAccess().getEGenericSuperTypesAssignment_13_2(), "rule__EClass__EGenericSuperTypesAssignment_13_2");
			builder.put(grammarAccess.getEClassAccess().getEGenericSuperTypesAssignment_13_3_1(), "rule__EClass__EGenericSuperTypesAssignment_13_3_1");
			builder.put(grammarAccess.getEOperationAccess().getNameAssignment_2(), "rule__EOperation__NameAssignment_2");
			builder.put(grammarAccess.getEOperationAccess().getOrderedAssignment_4_1(), "rule__EOperation__OrderedAssignment_4_1");
			builder.put(grammarAccess.getEOperationAccess().getUniqueAssignment_5_1(), "rule__EOperation__UniqueAssignment_5_1");
			builder.put(grammarAccess.getEOperationAccess().getLowerBoundAssignment_6_1(), "rule__EOperation__LowerBoundAssignment_6_1");
			builder.put(grammarAccess.getEOperationAccess().getUpperBoundAssignment_7_1(), "rule__EOperation__UpperBoundAssignment_7_1");
			builder.put(grammarAccess.getEOperationAccess().getETypeAssignment_8_1(), "rule__EOperation__ETypeAssignment_8_1");
			builder.put(grammarAccess.getEOperationAccess().getEExceptionsAssignment_9_2(), "rule__EOperation__EExceptionsAssignment_9_2");
			builder.put(grammarAccess.getEOperationAccess().getEExceptionsAssignment_9_3_1(), "rule__EOperation__EExceptionsAssignment_9_3_1");
			builder.put(grammarAccess.getEOperationAccess().getEAnnotationsAssignment_10_2(), "rule__EOperation__EAnnotationsAssignment_10_2");
			builder.put(grammarAccess.getEOperationAccess().getEAnnotationsAssignment_10_3_1(), "rule__EOperation__EAnnotationsAssignment_10_3_1");
			builder.put(grammarAccess.getEOperationAccess().getEGenericTypeAssignment_11_1(), "rule__EOperation__EGenericTypeAssignment_11_1");
			builder.put(grammarAccess.getEOperationAccess().getETypeParametersAssignment_12_2(), "rule__EOperation__ETypeParametersAssignment_12_2");
			builder.put(grammarAccess.getEOperationAccess().getETypeParametersAssignment_12_3_1(), "rule__EOperation__ETypeParametersAssignment_12_3_1");
			builder.put(grammarAccess.getEOperationAccess().getEParametersAssignment_13_2(), "rule__EOperation__EParametersAssignment_13_2");
			builder.put(grammarAccess.getEOperationAccess().getEParametersAssignment_13_3_1(), "rule__EOperation__EParametersAssignment_13_3_1");
			builder.put(grammarAccess.getEOperationAccess().getEGenericExceptionsAssignment_14_2(), "rule__EOperation__EGenericExceptionsAssignment_14_2");
			builder.put(grammarAccess.getEOperationAccess().getEGenericExceptionsAssignment_14_3_1(), "rule__EOperation__EGenericExceptionsAssignment_14_3_1");
			builder.put(grammarAccess.getEAnnotationAccess().getSourceAssignment_3_1(), "rule__EAnnotation__SourceAssignment_3_1");
			builder.put(grammarAccess.getEAnnotationAccess().getReferencesAssignment_4_2(), "rule__EAnnotation__ReferencesAssignment_4_2");
			builder.put(grammarAccess.getEAnnotationAccess().getReferencesAssignment_4_3_1(), "rule__EAnnotation__ReferencesAssignment_4_3_1");
			builder.put(grammarAccess.getEAnnotationAccess().getEAnnotationsAssignment_5_2(), "rule__EAnnotation__EAnnotationsAssignment_5_2");
			builder.put(grammarAccess.getEAnnotationAccess().getEAnnotationsAssignment_5_3_1(), "rule__EAnnotation__EAnnotationsAssignment_5_3_1");
			builder.put(grammarAccess.getEAnnotationAccess().getDetailsAssignment_6_2(), "rule__EAnnotation__DetailsAssignment_6_2");
			builder.put(grammarAccess.getEAnnotationAccess().getDetailsAssignment_6_3_1(), "rule__EAnnotation__DetailsAssignment_6_3_1");
			builder.put(grammarAccess.getEAnnotationAccess().getContentsAssignment_7_2(), "rule__EAnnotation__ContentsAssignment_7_2");
			builder.put(grammarAccess.getEAnnotationAccess().getContentsAssignment_7_3_1(), "rule__EAnnotation__ContentsAssignment_7_3_1");
			builder.put(grammarAccess.getETypeParameterAccess().getNameAssignment_2(), "rule__ETypeParameter__NameAssignment_2");
			builder.put(grammarAccess.getETypeParameterAccess().getEAnnotationsAssignment_4_2(), "rule__ETypeParameter__EAnnotationsAssignment_4_2");
			builder.put(grammarAccess.getETypeParameterAccess().getEAnnotationsAssignment_4_3_1(), "rule__ETypeParameter__EAnnotationsAssignment_4_3_1");
			builder.put(grammarAccess.getETypeParameterAccess().getEBoundsAssignment_5_2(), "rule__ETypeParameter__EBoundsAssignment_5_2");
			builder.put(grammarAccess.getETypeParameterAccess().getEBoundsAssignment_5_3_1(), "rule__ETypeParameter__EBoundsAssignment_5_3_1");
			builder.put(grammarAccess.getEGenericTypeAccess().getETypeParameterAssignment_3_1(), "rule__EGenericType__ETypeParameterAssignment_3_1");
			builder.put(grammarAccess.getEGenericTypeAccess().getEClassifierAssignment_4_1(), "rule__EGenericType__EClassifierAssignment_4_1");
			builder.put(grammarAccess.getEGenericTypeAccess().getEUpperBoundAssignment_5_1(), "rule__EGenericType__EUpperBoundAssignment_5_1");
			builder.put(grammarAccess.getEGenericTypeAccess().getETypeArgumentsAssignment_6_2(), "rule__EGenericType__ETypeArgumentsAssignment_6_2");
			builder.put(grammarAccess.getEGenericTypeAccess().getETypeArgumentsAssignment_6_3_1(), "rule__EGenericType__ETypeArgumentsAssignment_6_3_1");
			builder.put(grammarAccess.getEGenericTypeAccess().getELowerBoundAssignment_7_1(), "rule__EGenericType__ELowerBoundAssignment_7_1");
			builder.put(grammarAccess.getEStringToStringMapEntryAccess().getKeyAssignment_3_1(), "rule__EStringToStringMapEntry__KeyAssignment_3_1");
			builder.put(grammarAccess.getEStringToStringMapEntryAccess().getValueAssignment_4_1(), "rule__EStringToStringMapEntry__ValueAssignment_4_1");
			builder.put(grammarAccess.getEAttributeAccess().getVolatileAssignment_1(), "rule__EAttribute__VolatileAssignment_1");
			builder.put(grammarAccess.getEAttributeAccess().getTransientAssignment_2(), "rule__EAttribute__TransientAssignment_2");
			builder.put(grammarAccess.getEAttributeAccess().getUnsettableAssignment_3(), "rule__EAttribute__UnsettableAssignment_3");
			builder.put(grammarAccess.getEAttributeAccess().getDerivedAssignment_4(), "rule__EAttribute__DerivedAssignment_4");
			builder.put(grammarAccess.getEAttributeAccess().getIDAssignment_5(), "rule__EAttribute__IDAssignment_5");
			builder.put(grammarAccess.getEAttributeAccess().getNameAssignment_7(), "rule__EAttribute__NameAssignment_7");
			builder.put(grammarAccess.getEAttributeAccess().getOrderedAssignment_9_1(), "rule__EAttribute__OrderedAssignment_9_1");
			builder.put(grammarAccess.getEAttributeAccess().getUniqueAssignment_10_1(), "rule__EAttribute__UniqueAssignment_10_1");
			builder.put(grammarAccess.getEAttributeAccess().getLowerBoundAssignment_11_1(), "rule__EAttribute__LowerBoundAssignment_11_1");
			builder.put(grammarAccess.getEAttributeAccess().getUpperBoundAssignment_12_1(), "rule__EAttribute__UpperBoundAssignment_12_1");
			builder.put(grammarAccess.getEAttributeAccess().getChangeableAssignment_13_1(), "rule__EAttribute__ChangeableAssignment_13_1");
			builder.put(grammarAccess.getEAttributeAccess().getDefaultValueLiteralAssignment_14_1(), "rule__EAttribute__DefaultValueLiteralAssignment_14_1");
			builder.put(grammarAccess.getEAttributeAccess().getETypeAssignment_15_1(), "rule__EAttribute__ETypeAssignment_15_1");
			builder.put(grammarAccess.getEAttributeAccess().getEAnnotationsAssignment_16_2(), "rule__EAttribute__EAnnotationsAssignment_16_2");
			builder.put(grammarAccess.getEAttributeAccess().getEAnnotationsAssignment_16_3_1(), "rule__EAttribute__EAnnotationsAssignment_16_3_1");
			builder.put(grammarAccess.getEAttributeAccess().getEGenericTypeAssignment_17_1(), "rule__EAttribute__EGenericTypeAssignment_17_1");
			builder.put(grammarAccess.getEReferenceAccess().getVolatileAssignment_1(), "rule__EReference__VolatileAssignment_1");
			builder.put(grammarAccess.getEReferenceAccess().getTransientAssignment_2(), "rule__EReference__TransientAssignment_2");
			builder.put(grammarAccess.getEReferenceAccess().getUnsettableAssignment_3(), "rule__EReference__UnsettableAssignment_3");
			builder.put(grammarAccess.getEReferenceAccess().getDerivedAssignment_4(), "rule__EReference__DerivedAssignment_4");
			builder.put(grammarAccess.getEReferenceAccess().getContainmentAssignment_5(), "rule__EReference__ContainmentAssignment_5");
			builder.put(grammarAccess.getEReferenceAccess().getNameAssignment_7(), "rule__EReference__NameAssignment_7");
			builder.put(grammarAccess.getEReferenceAccess().getOrderedAssignment_9_1(), "rule__EReference__OrderedAssignment_9_1");
			builder.put(grammarAccess.getEReferenceAccess().getUniqueAssignment_10_1(), "rule__EReference__UniqueAssignment_10_1");
			builder.put(grammarAccess.getEReferenceAccess().getLowerBoundAssignment_11_1(), "rule__EReference__LowerBoundAssignment_11_1");
			builder.put(grammarAccess.getEReferenceAccess().getUpperBoundAssignment_12_1(), "rule__EReference__UpperBoundAssignment_12_1");
			builder.put(grammarAccess.getEReferenceAccess().getChangeableAssignment_13_1(), "rule__EReference__ChangeableAssignment_13_1");
			builder.put(grammarAccess.getEReferenceAccess().getDefaultValueLiteralAssignment_14_1(), "rule__EReference__DefaultValueLiteralAssignment_14_1");
			builder.put(grammarAccess.getEReferenceAccess().getResolveProxiesAssignment_15_1(), "rule__EReference__ResolveProxiesAssignment_15_1");
			builder.put(grammarAccess.getEReferenceAccess().getETypeAssignment_16_1(), "rule__EReference__ETypeAssignment_16_1");
			builder.put(grammarAccess.getEReferenceAccess().getEOppositeAssignment_17_1(), "rule__EReference__EOppositeAssignment_17_1");
			builder.put(grammarAccess.getEReferenceAccess().getEKeysAssignment_18_2(), "rule__EReference__EKeysAssignment_18_2");
			builder.put(grammarAccess.getEReferenceAccess().getEKeysAssignment_18_3_1(), "rule__EReference__EKeysAssignment_18_3_1");
			builder.put(grammarAccess.getEReferenceAccess().getEAnnotationsAssignment_19_2(), "rule__EReference__EAnnotationsAssignment_19_2");
			builder.put(grammarAccess.getEReferenceAccess().getEAnnotationsAssignment_19_3_1(), "rule__EReference__EAnnotationsAssignment_19_3_1");
			builder.put(grammarAccess.getEReferenceAccess().getEGenericTypeAssignment_20_1(), "rule__EReference__EGenericTypeAssignment_20_1");
			builder.put(grammarAccess.getEDataType_ImplAccess().getNameAssignment_2(), "rule__EDataType_Impl__NameAssignment_2");
			builder.put(grammarAccess.getEDataType_ImplAccess().getInstanceClassNameAssignment_4_1(), "rule__EDataType_Impl__InstanceClassNameAssignment_4_1");
			builder.put(grammarAccess.getEDataType_ImplAccess().getInstanceTypeNameAssignment_5_1(), "rule__EDataType_Impl__InstanceTypeNameAssignment_5_1");
			builder.put(grammarAccess.getEDataType_ImplAccess().getSerializableAssignment_6_1(), "rule__EDataType_Impl__SerializableAssignment_6_1");
			builder.put(grammarAccess.getEDataType_ImplAccess().getEAnnotationsAssignment_7_2(), "rule__EDataType_Impl__EAnnotationsAssignment_7_2");
			builder.put(grammarAccess.getEDataType_ImplAccess().getEAnnotationsAssignment_7_3_1(), "rule__EDataType_Impl__EAnnotationsAssignment_7_3_1");
			builder.put(grammarAccess.getEDataType_ImplAccess().getETypeParametersAssignment_8_2(), "rule__EDataType_Impl__ETypeParametersAssignment_8_2");
			builder.put(grammarAccess.getEDataType_ImplAccess().getETypeParametersAssignment_8_3_1(), "rule__EDataType_Impl__ETypeParametersAssignment_8_3_1");
			builder.put(grammarAccess.getEEnumAccess().getNameAssignment_2(), "rule__EEnum__NameAssignment_2");
			builder.put(grammarAccess.getEEnumAccess().getInstanceClassNameAssignment_4_1(), "rule__EEnum__InstanceClassNameAssignment_4_1");
			builder.put(grammarAccess.getEEnumAccess().getInstanceTypeNameAssignment_5_1(), "rule__EEnum__InstanceTypeNameAssignment_5_1");
			builder.put(grammarAccess.getEEnumAccess().getSerializableAssignment_6_1(), "rule__EEnum__SerializableAssignment_6_1");
			builder.put(grammarAccess.getEEnumAccess().getEAnnotationsAssignment_7_2(), "rule__EEnum__EAnnotationsAssignment_7_2");
			builder.put(grammarAccess.getEEnumAccess().getEAnnotationsAssignment_7_3_1(), "rule__EEnum__EAnnotationsAssignment_7_3_1");
			builder.put(grammarAccess.getEEnumAccess().getETypeParametersAssignment_8_2(), "rule__EEnum__ETypeParametersAssignment_8_2");
			builder.put(grammarAccess.getEEnumAccess().getETypeParametersAssignment_8_3_1(), "rule__EEnum__ETypeParametersAssignment_8_3_1");
			builder.put(grammarAccess.getEEnumAccess().getELiteralsAssignment_9_2(), "rule__EEnum__ELiteralsAssignment_9_2");
			builder.put(grammarAccess.getEEnumAccess().getELiteralsAssignment_9_3_1(), "rule__EEnum__ELiteralsAssignment_9_3_1");
			builder.put(grammarAccess.getEEnumLiteralAccess().getNameAssignment_2(), "rule__EEnumLiteral__NameAssignment_2");
			builder.put(grammarAccess.getEEnumLiteralAccess().getValueAssignment_4_1(), "rule__EEnumLiteral__ValueAssignment_4_1");
			builder.put(grammarAccess.getEEnumLiteralAccess().getLiteralAssignment_5_1(), "rule__EEnumLiteral__LiteralAssignment_5_1");
			builder.put(grammarAccess.getEEnumLiteralAccess().getEAnnotationsAssignment_6_2(), "rule__EEnumLiteral__EAnnotationsAssignment_6_2");
			builder.put(grammarAccess.getEEnumLiteralAccess().getEAnnotationsAssignment_6_3_1(), "rule__EEnumLiteral__EAnnotationsAssignment_6_3_1");
			builder.put(grammarAccess.getEParameterAccess().getNameAssignment_2(), "rule__EParameter__NameAssignment_2");
			builder.put(grammarAccess.getEParameterAccess().getOrderedAssignment_4_1(), "rule__EParameter__OrderedAssignment_4_1");
			builder.put(grammarAccess.getEParameterAccess().getUniqueAssignment_5_1(), "rule__EParameter__UniqueAssignment_5_1");
			builder.put(grammarAccess.getEParameterAccess().getLowerBoundAssignment_6_1(), "rule__EParameter__LowerBoundAssignment_6_1");
			builder.put(grammarAccess.getEParameterAccess().getUpperBoundAssignment_7_1(), "rule__EParameter__UpperBoundAssignment_7_1");
			builder.put(grammarAccess.getEParameterAccess().getETypeAssignment_8_1(), "rule__EParameter__ETypeAssignment_8_1");
			builder.put(grammarAccess.getEParameterAccess().getEAnnotationsAssignment_9_2(), "rule__EParameter__EAnnotationsAssignment_9_2");
			builder.put(grammarAccess.getEParameterAccess().getEAnnotationsAssignment_9_3_1(), "rule__EParameter__EAnnotationsAssignment_9_3_1");
			builder.put(grammarAccess.getEParameterAccess().getEGenericTypeAssignment_10_1(), "rule__EParameter__EGenericTypeAssignment_10_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private EelGrammarAccess grammarAccess;

	@Override
	protected InternalEelParser createParser() {
		InternalEelParser result = new InternalEelParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public EelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
