/**
 * generated by Xtext 2.14.0
 */
package fr.tblf.energy.estimation.eel.ide;

import fr.tblf.energy.estimation.eel.ide.AbstractEelIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EelIdeModule extends AbstractEelIdeModule {
}
