/**
 * generated by Xtext 2.14.0
 */
package fr.tblf.energy.estimation.eel.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.tblf.energy.estimation.eel.EelRuntimeModule;
import fr.tblf.energy.estimation.eel.EelStandaloneSetup;
import fr.tblf.energy.estimation.eel.ide.EelIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class EelIdeSetup extends EelStandaloneSetup {
  @Override
  public Injector createInjector() {
    EelRuntimeModule _eelRuntimeModule = new EelRuntimeModule();
    EelIdeModule _eelIdeModule = new EelIdeModule();
    return Guice.createInjector(Modules2.mixin(_eelRuntimeModule, _eelIdeModule));
  }
}
