/**
 * generated by Xtext 2.14.0
 */
package fr.tblf.energy.estimation.eel.ui;

import fr.tblf.energy.estimation.eel.ui.AbstractEelUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class EelUiModule extends AbstractEelUiModule {
  public EelUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
