/*
 * generated by Xtext 2.14.0
 */
package fr.tblf.energy.estimation.eel.ui.tests;

import com.google.inject.Injector;
import fr.tblf.energy.estimation.eel.ui.internal.EelActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class EelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EelActivator.getInstance().getInjector("fr.tblf.energy.estimation.eel.Eel");
	}

}
