/*
 * generated by Xtext 2.14.0
 */
package org.atlanmod.energy.estimation.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EelAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/atlanmod/energy/estimation/dsl/parser/antlr/internal/InternalEel.tokens");
	}
}
