/*
 * generated by Xtext 2.14.0
 */
package fr.tblf.energy.estimation.ide

import com.google.inject.Guice
import fr.tblf.energy.estimation.EelRuntimeModule
import fr.tblf.energy.estimation.EelStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class EelIdeSetup extends EelStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new EelRuntimeModule, new EelIdeModule))
	}
	
}
